### ISSUE TITLE
Incorrect package check downloads and reinstalls it

### ISSUE THREAD

**Issue by bdovaz** [DragonBox/u3d#198] opened 2017-12-24 11:13 UTC
If I run on Windows, for example:

u3d install 2017.3.0f3 -p Mac
u3d install 2017.3.0f3 -p Linux
u3d install 2017.3.0f3 -p iOS

Always installs it but for other packages like Android or WebGL it says that it's already installed so it skips it like it should do for Mac, Linux or iOS.

I want in Jenkins to always run this command on my builds before running Unity so I can be sure that it's already installed. But if it's going to install it every time I run that command despite of being already installed it's not worth it because it takes some minutes to install something that it was already installed.

Also, it would be nice for download packages to:
- Allow to select the folder where we want to download it.
- Allow to delete the download packages after a correct installation.

In our case we use it in CI servers that we don't want to fill the hard drive with Unity installation files.

Thanks for you hard work, it's a really nice tool.

**Comment by lacostej** [comment] 2017-12-24 15:04
Hello @bdovaz, WRT to it always reinstalling, I understand your need. The issue is known and is described #161 (which I marked as non fix). I think I will have to reevaluate it then. If you feel like helping, let us know.

**Comment by bdovaz** [comment] 2017-12-24 15:25
Seeing the other issue I see that it's because ivy.xml module name doesn't match with the Package name.

Can't you simply create a map?

- iOS -> iPhone
- Mac -> StandaloneOSX
- Etc.

**Comment by niezbop** [comment] 2017-12-24 15:35
We thought about doing that, but that will not be perfect. It will still install things such as the Documentation and the Standard Assets, which are not tracked in the `ivy.xml`. I'm going to check how hard it would be to detect those, even though it could be quite clunky.

**Comment by bdovaz** [comment] 2017-12-24 15:58
I've also access to 2018.1b and I see that in 2017.3 marked as deprecated StandaloneOSXIntel and StandaloneOSXIntel64 and StandaloneOSXUniversal became in 2018.1b StandaloneOSX as a unique target.

I say this because depending on Unity version the mapping should be different or allow to map to N targets like: Mac -> [StandaloneOSXIntel, StandaloneOSXIntel64, StandaloneOSX]

**Comment by niezbop** [comment] 2017-12-24 16:07
Okay I'll take a look at that. I've started some stuff on my side to see how easy it would be to find Standard Assets and Documentation: https://github.com/niezbop/u3d/commit/972b8603b984e030494298cf6854cd2e6b1c3d6b if you want to take a look at it, it shouldn't be too hard. 

I'm not available right now to take a look at the mapping issue, but if you want to work on that, the only line that matters to you is [this one](https://github.com/DragonBox/u3d/blob/master/lib/u3d/commands.rb#L332).

**Comment by niezbop** [comment] 2017-12-24 16:36
So, I'm working on package mapping https://github.com/niezbop/u3d/commit/86827fd9adf89c9cb034cf6563652c2eea2f8045 . Feel free to open PRs on my branch https://github.com/niezbop/u3d/tree/package_detection if you want to compete it. I'll work on that later.

**Comment by lacostej** [comment] 2017-12-25 11:54
I installed all packages in latest 2017.3

```
$ u3d available -p -u 2017.3.0f3 
Version 2017.3.0f3: https://netstorage.unity3d.com/unity/a9f86dcd79df/
Packages:
 - Unity
 - MonoDevelop
 - Documentation
 - StandardAssets
 - Example
 - Android
 - iOS
 - AppleTV
 - Linux
 - Vuforia-AR
 - WebGL
 - Windows
 - Facebook-Games
$ u3d install -a 2017.3.0f3
....
$ u3d list -p
....
Version 2017.3.0f3                    (/Applications/Unity_2017.3.0f3)
Packages:
 - Android
 - tvOS
 - Facebook
 - iPhone
 - StandaloneLinux
 - UnityExtensions
 - WebGL
 - StandaloneWindows
```

Some notes
* MonoDevelop, MonoDevelop, StandardAssets, Example goes into its own space
* UnityExtensions is Vuforia

**Closed** 2018-01-02 11:56 UTC

**Comment by niezbop** [comment] 2018-01-02 13:57
Hey @bdovaz ! I believe that #202 should solve your issue 😃 It was not that big a deal, but holidays with limited Internet got in the way!

**Comment by lacostej** [comment] 2018-01-03 09:13
@bdovaz the requested feature was added and released as part of 1.0.12. Thanks for the feedback!

**Comment by bdovaz** [comment] 2018-01-05 15:30
Thanks @lacostej !! I'm using it and it's great!!

It would be nice also to provide like I said in my first message a way to provide a custom path for downloaded packages. In our organization we share a network drive where we store heavy installers and packages. When you are using it in your own machine it makes sense to go to "Downloads" folder but on a CI server you should be able to provide a custom path.

And also a way to delete them if we want with some flag.

**Comment by lacostej** [comment] 2018-01-05 17:44
@bdovaz yes go ahead. Please note that there's a way for you to download packages on one computer and install on another one. Maybe something you want to use on your server.
