### ISSUE TITLE
[Feature request] List available packages

### ISSUE THREAD

**Issue by exlee** [DragonBox/u3d#70] opened 2017-08-18 10:26 UTC
When installing there is no information what kind of packages can be installed with `-p` option.

It would be great if those could be listed either globally or package-by-package.

**Comment by niezbop** [comment] 2017-08-20 09:17
Working as intended on `master`; this may be related to 0.9.3. Closing the issue for now.

**Closed by niezbop** 2017-08-20 09:17 UTC

**Comment by wofwof** [comment] 2017-11-27 11:07
Hey, i also would like to put my hands on the list of packages that can be instaled :) I had a problem with "iOS" as I was typing "IOS".

**Comment by niezbop** [comment] 2017-11-27 12:20
Hey :) This feature is already implemented!

You can run `u3d available --packages` or `u3d available -p` for short to see available packages for each version of Unity. They are all in the correct syntax for you to use. If you want to check the available packages for a specific version of Unity you can run `u3d available -u <VERSION> -p`.

Remember that if you need help on u3d, you can always run `u3d --help` or help on a specific command, `u3d <COMMAND> --help`.

I hope this helps!

**Comment by wofwof** [comment] 2017-11-27 12:35
Thank You!
